# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

java_binary(
    name = "exc-one",
    main_class = "one.prio.exc.one.Main",
    deps = [":main"],
)

java_library(
    name = "main",
    srcs = glob(["*.java"]),
)
